branch-defaults:
  default:
    environment: udagrama-api-dev
environment-defaults:
  udagrama-api-dev:
    branch: null
    repository: null
global:
  application_name: udagrama-api
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
